### ISSUE TITLE
Is the raw OrderBooks not implemented

### ISSUE THREAD

**Issue by JoshuaBatty** [wisespace-io/bitfinex-rs#1]
Hi there, just trying to subscribe to the Raw Orderbooks and having some trouble. Before I start hacking away just checking if this is implemented already for this => https://docs.bitfinex.com/v2/reference#ws-public-raw-order-books

I'm assuming BookTradingUpdateEvent is what gets matched on here but I can't seem to tell. Cheers.

**Comment by wisespace-io** [comment]
@JoshuaBatty it is NOT implemented. The request is different, so you will need:

1. Update websockets.rs and add a new subscribe method:

```
    pub fn subscribe_raw_books<S>(&mut self, symbol: S, et: EventType)
        where S: Into<String> 
    {
        let msg = json!(
            {
                "event": "subscribe", 
                "channel": "book", 
                "pair": self.format_symbol(symbol.into(), et),
                "prec": "R0"
            });

        if let Err(error_msg) = self.sender.send(&msg.to_string()) {
            self.error_hander(error_msg);
        }
    }
```

Note: The algorithm for raw books is based on "R0", so I guess we can hardcode it.

2. Add a new struct to book.rs as it streams order_id, price and amount

```
    // Trading: if AMOUNT > 0 then bid else ask; Funding: if AMOUNT < 0 then bid else ask;
    #[derive(Serialize, Deserialize, Debug)]
    pub struct RawBook {
        pub order_id: i64,
        pub price: f64,
        pub amount: f64,
    }
```

3. Update events.rs and add 2 new entries to the Enum DataEvent

```
    RawBookEvent (i32, RawBook),
    RawBookUpdateEvent (i32, Vec<RawBook>),
```

4. In order to test, update on_data_event in public_channels.rs to handle the Event and UpdateEvent added above ...

```
        } else if let DataEvent::RawBookEvent(channel, raw_book) = event {
            println!("Rawbook Event ({}) - {:?}", channel, raw_book);
        }  ....
```

Please submit a Pull Request if it works, together with any other changes, so we can add it to the library.

**Comment by JoshuaBatty** [comment]
@wisespace-io thanks a bunch this works great. Had to change the order of the json message to subscribe but after that everything works perfectly. I've opened a pull request so feel free to merge when you're ready.
